name = "daemon"
main = "src/worker.ts"
compatibility_date = "2025-08-20"
workers_dev = false

# Custom domain route
routes = [
  { pattern = "daemon.kheerand.id.au", custom_domain = true }
]

[site]
bucket = "./dist"

# Pages configuration
pages_build_output_dir = "./dist"

[observability]
enabled = false
